
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int pyc = 8;
  public static final int parc = 11;
  public static final int cadena = 18;
  public static final int para = 10;
  public static final int unario = 19;
  public static final int decimal = 16;
  public static final int por = 4;
  public static final int menos = 3;
  public static final int digito = 15;
  public static final int div = 5;
  public static final int menorque = 6;
  public static final int igual = 9;
  public static final int EOF = 0;
  public static final int id = 17;
  public static final int mayorque = 7;
  public static final int error = 1;
  public static final int js_let = 12;
  public static final int js_const = 13;
  public static final int mas = 2;
  public static final int js_var = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "mas",
  "menos",
  "por",
  "div",
  "menorque",
  "mayorque",
  "pyc",
  "igual",
  "para",
  "parc",
  "js_let",
  "js_const",
  "js_var",
  "digito",
  "decimal",
  "id",
  "cadena",
  "unario"
  };
}

