
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int div = 4;
  public static final int digito = 12;
  public static final int corc = 8;
  public static final int unario = 13;
  public static final int cora = 7;
  public static final int EOF = 0;
  public static final int menos = 5;
  public static final int error = 1;
  public static final int por = 3;
  public static final int eval = 11;
  public static final int parc = 10;
  public static final int mas = 2;
  public static final int pyc = 6;
  public static final int para = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "mas",
  "por",
  "div",
  "menos",
  "pyc",
  "cora",
  "corc",
  "para",
  "parc",
  "eval",
  "digito",
  "unario"
  };
}

