
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos_FCA {
  /* terminals */
  public static final int pyc = 7;
  public static final int parc = 6;
  public static final int para = 5;
  public static final int cadena = 10;
  public static final int decimal = 18;
  public static final int coma = 2;
  public static final int dospnts = 20;
  public static final int tituloy = 16;
  public static final int titulox = 15;
  public static final int titulo = 12;
  public static final int llavc = 4;
  public static final int llava = 3;
  public static final int ejex = 13;
  public static final int digito = 17;
  public static final int EOF = 0;
  public static final int id = 19;
  public static final int gre = 8;
  public static final int error = 1;
  public static final int gbarras = 11;
  public static final int corc = 22;
  public static final int comp = 9;
  public static final int valores = 14;
  public static final int cora = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "coma",
  "llava",
  "llavc",
  "para",
  "parc",
  "pyc",
  "gre",
  "comp",
  "cadena",
  "gbarras",
  "titulo",
  "ejex",
  "valores",
  "titulox",
  "tituloy",
  "digito",
  "decimal",
  "id",
  "dospnts",
  "cora",
  "corc"
  };
}

