
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

import java_cup.runtime.Symbol;
import olc1_clase4.Comparar;
import java.util.LinkedList;
import Reportes.Caracteristica;
import Reportes.GBarras;
import Reportes.Valor;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Sintactico_FCA extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return Simbolos_FCA.class;
}

  /** Default constructor. */
  @Deprecated
  public Sintactico_FCA() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Sintactico_FCA(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Sintactico_FCA(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\025\000\002\002\004\000\002\002\006\000\002\003" +
    "\004\000\002\003\003\000\002\004\003\000\002\004\003" +
    "\000\002\005\011\000\002\006\006\000\002\007\004\000" +
    "\002\007\003\000\002\010\006\000\002\010\010\000\002" +
    "\010\010\000\002\010\006\000\002\010\006\000\002\011" +
    "\005\000\002\011\003\000\002\012\003\000\002\012\003" +
    "\000\002\012\003\000\002\012\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\067\000\004\012\004\001\002\000\004\005\007\001" +
    "\002\000\004\002\006\001\002\000\004\002\001\001\002" +
    "\000\006\013\011\015\010\001\002\000\004\005\026\001" +
    "\002\000\004\007\020\001\002\000\010\006\ufffd\013\ufffd" +
    "\015\ufffd\001\002\000\010\006\ufffe\013\ufffe\015\ufffe\001" +
    "\002\000\010\006\017\013\011\015\010\001\002\000\010" +
    "\006\ufffc\013\ufffc\015\ufffc\001\002\000\010\006\uffff\013" +
    "\uffff\015\uffff\001\002\000\004\002\000\001\002\000\004" +
    "\014\021\001\002\000\004\004\022\001\002\000\004\014" +
    "\023\001\002\000\004\010\024\001\002\000\004\011\025" +
    "\001\002\000\010\006\ufffb\013\ufffb\015\ufffb\001\002\000" +
    "\014\016\030\017\031\020\034\021\035\022\033\001\002" +
    "\000\016\006\ufff8\016\ufff8\017\ufff8\020\ufff8\021\ufff8\022" +
    "\ufff8\001\002\000\004\026\067\001\002\000\004\026\062" +
    "\001\002\000\016\006\061\016\030\017\031\020\034\021" +
    "\035\022\033\001\002\000\004\026\055\001\002\000\004" +
    "\026\045\001\002\000\004\026\036\001\002\000\012\014" +
    "\041\023\037\024\040\025\043\001\002\000\010\004\uffef" +
    "\011\uffef\030\uffef\001\002\000\010\004\ufff0\011\ufff0\030" +
    "\ufff0\001\002\000\010\004\uffed\011\uffed\030\uffed\001\002" +
    "\000\004\011\044\001\002\000\010\004\uffee\011\uffee\030" +
    "\uffee\001\002\000\016\006\ufff4\016\ufff4\017\ufff4\020\ufff4" +
    "\021\ufff4\022\ufff4\001\002\000\004\027\046\001\002\000" +
    "\012\014\041\023\037\024\040\025\043\001\002\000\006" +
    "\004\052\030\051\001\002\000\006\004\ufff1\030\ufff1\001" +
    "\002\000\004\011\054\001\002\000\012\014\041\023\037" +
    "\024\040\025\043\001\002\000\006\004\ufff2\030\ufff2\001" +
    "\002\000\016\006\ufff5\016\ufff5\017\ufff5\020\ufff5\021\ufff5" +
    "\022\ufff5\001\002\000\012\014\041\023\037\024\040\025" +
    "\043\001\002\000\004\011\057\001\002\000\016\006\ufff3" +
    "\016\ufff3\017\ufff3\020\ufff3\021\ufff3\022\ufff3\001\002\000" +
    "\016\006\ufff9\016\ufff9\017\ufff9\020\ufff9\021\ufff9\022\ufff9" +
    "\001\002\000\010\006\ufffa\013\ufffa\015\ufffa\001\002\000" +
    "\004\027\063\001\002\000\012\014\041\023\037\024\040" +
    "\025\043\001\002\000\006\004\052\030\065\001\002\000" +
    "\004\011\066\001\002\000\016\006\ufff6\016\ufff6\017\ufff6" +
    "\020\ufff6\021\ufff6\022\ufff6\001\002\000\012\014\041\023" +
    "\037\024\040\025\043\001\002\000\004\011\071\001\002" +
    "\000\016\006\ufff7\016\ufff7\017\ufff7\020\ufff7\021\ufff7\022" +
    "\ufff7\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\067\000\004\002\004\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\012\003\013\004\012" +
    "\005\011\006\014\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\004\015" +
    "\005\011\006\014\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\007\031\010\026\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\010" +
    "\057\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\012\041\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\011" +
    "\046\012\047\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\012\052\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\012\055\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\011\063\012\047\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\012\067\001\001\000\002\001\001\000\002\001\001" +
    "" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Sintactico_FCA$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Sintactico_FCA$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Sintactico_FCA$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



        public String resultado = "";
        public static LinkedList<Object> instrucciones;
        
        

        public void syntax_error(Symbol s)
        {
            System.err.println("Error en la Linea " + (s.right+1) +" Columna "+(s.left+1)+ ". Identificador "+s.value + " no reconocido. Se ha recuperado del error." );
        }

        public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception
        {
            System.err.println("Error en la Linea " + (s.right+1)+ " Columna "+(s.left+1)+". Identificador " +s.value + " no reconocido.");
        }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Sintactico_FCA$actions {

  
  private final Sintactico_FCA parser;

  /** Constructor */
  CUP$Sintactico_FCA$actions(Sintactico_FCA parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Sintactico_FCA$do_action_part00000000(
    int                        CUP$Sintactico_FCA$act_num,
    java_cup.runtime.lr_parser CUP$Sintactico_FCA$parser,
    java.util.Stack            CUP$Sintactico_FCA$stack,
    int                        CUP$Sintactico_FCA$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Sintactico_FCA$result;

      /* select the action based on the action number */
      switch (CUP$Sintactico_FCA$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)).value;
		RESULT = start_val;
              CUP$Sintactico_FCA$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Sintactico_FCA$parser.done_parsing();
          return CUP$Sintactico_FCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= gre llava INSTRUCCIONES llavc 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)).right;
		LinkedList<Object> a = (LinkedList<Object>)((java_cup.runtime.Symbol) CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)).value;
		 instrucciones = a;  
              CUP$Sintactico_FCA$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), RESULT);
            }
          return CUP$Sintactico_FCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // INSTRUCCIONES ::= INSTRUCCIONES INSTRUCCION 
            {
              LinkedList<Object> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)).right;
		LinkedList<Object> a = (LinkedList<Object>)((java_cup.runtime.Symbol) CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$Sintactico_FCA$stack.peek()).value;
		 RESULT = a; RESULT.add(b); 
              CUP$Sintactico_FCA$result = parser.getSymbolFactory().newSymbol("INSTRUCCIONES",1, ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), RESULT);
            }
          return CUP$Sintactico_FCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // INSTRUCCIONES ::= INSTRUCCION 
            {
              LinkedList<Object> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$Sintactico_FCA$stack.peek()).value;
		 RESULT = new LinkedList<>(); RESULT.add(a);  
              CUP$Sintactico_FCA$result = parser.getSymbolFactory().newSymbol("INSTRUCCIONES",1, ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), RESULT);
            }
          return CUP$Sintactico_FCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // INSTRUCCION ::= COMPARE 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()).right;
		Comparar a = (Comparar)((java_cup.runtime.Symbol) CUP$Sintactico_FCA$stack.peek()).value;
		 RESULT = a; 
              CUP$Sintactico_FCA$result = parser.getSymbolFactory().newSymbol("INSTRUCCION",2, ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), RESULT);
            }
          return CUP$Sintactico_FCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // INSTRUCCION ::= GRAFICA_BARRAS 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()).right;
		GBarras a = (GBarras)((java_cup.runtime.Symbol) CUP$Sintactico_FCA$stack.peek()).value;
		 RESULT = a; 
              CUP$Sintactico_FCA$result = parser.getSymbolFactory().newSymbol("INSTRUCCION",2, ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), RESULT);
            }
          return CUP$Sintactico_FCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // COMPARE ::= comp para cadena coma cadena parc pyc 
            {
              Comparar RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-4)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-4)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-4)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-2)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-2)).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-2)).value;
		 RESULT = new Comparar(a.substring(1,a.length()-1),b.substring(1,b.length()-1)); //le quitamos las comillas a las cadenas 
              CUP$Sintactico_FCA$result = parser.getSymbolFactory().newSymbol("COMPARE",3, ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-6)), ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), RESULT);
            }
          return CUP$Sintactico_FCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // GRAFICA_BARRAS ::= gbarras llava CARACTERISTICAS llavc 
            {
              GBarras RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)).right;
		LinkedList<Caracteristica> a = (LinkedList<Caracteristica>)((java_cup.runtime.Symbol) CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)).value;
		 RESULT = new GBarras(a); 
              CUP$Sintactico_FCA$result = parser.getSymbolFactory().newSymbol("GRAFICA_BARRAS",4, ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), RESULT);
            }
          return CUP$Sintactico_FCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // CARACTERISTICAS ::= CARACTERISTICAS CARACTERISTICA 
            {
              LinkedList<Caracteristica> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)).right;
		LinkedList<Caracteristica> a = (LinkedList<Caracteristica>)((java_cup.runtime.Symbol) CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()).right;
		Caracteristica b = (Caracteristica)((java_cup.runtime.Symbol) CUP$Sintactico_FCA$stack.peek()).value;
		 RESULT = a; RESULT.add(b); 
              CUP$Sintactico_FCA$result = parser.getSymbolFactory().newSymbol("CARACTERISTICAS",5, ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), RESULT);
            }
          return CUP$Sintactico_FCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // CARACTERISTICAS ::= CARACTERISTICA 
            {
              LinkedList<Caracteristica> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()).right;
		Caracteristica a = (Caracteristica)((java_cup.runtime.Symbol) CUP$Sintactico_FCA$stack.peek()).value;
		 RESULT = new LinkedList<>(); RESULT.add(a);  
              CUP$Sintactico_FCA$result = parser.getSymbolFactory().newSymbol("CARACTERISTICAS",5, ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), RESULT);
            }
          return CUP$Sintactico_FCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // CARACTERISTICA ::= titulo dospnts VALOR pyc 
            {
              Caracteristica RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)).right;
		Valor a = (Valor)((java_cup.runtime.Symbol) CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)).value;
		 RESULT = new Caracteristica(0,a); 
              CUP$Sintactico_FCA$result = parser.getSymbolFactory().newSymbol("CARACTERISTICA",6, ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), RESULT);
            }
          return CUP$Sintactico_FCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // CARACTERISTICA ::= ejex dospnts cora VALORES corc pyc 
            {
              Caracteristica RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-2)).right;
		LinkedList<Valor> a = (LinkedList<Valor>)((java_cup.runtime.Symbol) CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-2)).value;
		 RESULT = new Caracteristica(1,a); 
              CUP$Sintactico_FCA$result = parser.getSymbolFactory().newSymbol("CARACTERISTICA",6, ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-5)), ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), RESULT);
            }
          return CUP$Sintactico_FCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // CARACTERISTICA ::= valores dospnts cora VALORES corc pyc 
            {
              Caracteristica RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-2)).right;
		LinkedList<Valor> a = (LinkedList<Valor>)((java_cup.runtime.Symbol) CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-2)).value;
		 RESULT = new Caracteristica(2,a); 
              CUP$Sintactico_FCA$result = parser.getSymbolFactory().newSymbol("CARACTERISTICA",6, ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-5)), ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), RESULT);
            }
          return CUP$Sintactico_FCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // CARACTERISTICA ::= titulox dospnts VALOR pyc 
            {
              Caracteristica RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)).right;
		Valor a = (Valor)((java_cup.runtime.Symbol) CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)).value;
		 RESULT = new Caracteristica(3,a); 
              CUP$Sintactico_FCA$result = parser.getSymbolFactory().newSymbol("CARACTERISTICA",6, ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), RESULT);
            }
          return CUP$Sintactico_FCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // CARACTERISTICA ::= tituloy dospnts VALOR pyc 
            {
              Caracteristica RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)).right;
		Valor a = (Valor)((java_cup.runtime.Symbol) CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)).value;
		 RESULT = new Caracteristica(4,a); 
              CUP$Sintactico_FCA$result = parser.getSymbolFactory().newSymbol("CARACTERISTICA",6, ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), RESULT);
            }
          return CUP$Sintactico_FCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // VALORES ::= VALORES coma VALOR 
            {
              LinkedList<Valor> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-2)).right;
		LinkedList<Valor> a = (LinkedList<Valor>)((java_cup.runtime.Symbol) CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()).right;
		Valor b = (Valor)((java_cup.runtime.Symbol) CUP$Sintactico_FCA$stack.peek()).value;
		 RESULT = a; RESULT.add(b); 
              CUP$Sintactico_FCA$result = parser.getSymbolFactory().newSymbol("VALORES",7, ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), RESULT);
            }
          return CUP$Sintactico_FCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // VALORES ::= VALOR 
            {
              LinkedList<Valor> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()).right;
		Valor a = (Valor)((java_cup.runtime.Symbol) CUP$Sintactico_FCA$stack.peek()).value;
		 RESULT = new LinkedList<>(); RESULT.add(a);  
              CUP$Sintactico_FCA$result = parser.getSymbolFactory().newSymbol("VALORES",7, ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), RESULT);
            }
          return CUP$Sintactico_FCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // VALOR ::= decimal 
            {
              Valor RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$Sintactico_FCA$stack.peek()).value;
		 RESULT = new Valor(1, new Double(a)); 
              CUP$Sintactico_FCA$result = parser.getSymbolFactory().newSymbol("VALOR",8, ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), RESULT);
            }
          return CUP$Sintactico_FCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // VALOR ::= digito 
            {
              Valor RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$Sintactico_FCA$stack.peek()).value;
		 RESULT = new Valor(2, new Integer(a)); 
              CUP$Sintactico_FCA$result = parser.getSymbolFactory().newSymbol("VALOR",8, ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), RESULT);
            }
          return CUP$Sintactico_FCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // VALOR ::= id 
            {
              Valor RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$Sintactico_FCA$stack.peek()).value;
		 RESULT = new Valor(3, a); 
              CUP$Sintactico_FCA$result = parser.getSymbolFactory().newSymbol("VALOR",8, ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), RESULT);
            }
          return CUP$Sintactico_FCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // VALOR ::= cadena 
            {
              Valor RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$Sintactico_FCA$stack.peek()).value;
		 RESULT = new Valor(4, a.substring(1,a.length()-1)); 
              CUP$Sintactico_FCA$result = parser.getSymbolFactory().newSymbol("VALOR",8, ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), RESULT);
            }
          return CUP$Sintactico_FCA$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Sintactico_FCA$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Sintactico_FCA$do_action(
    int                        CUP$Sintactico_FCA$act_num,
    java_cup.runtime.lr_parser CUP$Sintactico_FCA$parser,
    java.util.Stack            CUP$Sintactico_FCA$stack,
    int                        CUP$Sintactico_FCA$top)
    throws java.lang.Exception
    {
              return CUP$Sintactico_FCA$do_action_part00000000(
                               CUP$Sintactico_FCA$act_num,
                               CUP$Sintactico_FCA$parser,
                               CUP$Sintactico_FCA$stack,
                               CUP$Sintactico_FCA$top);
    }
}

}
