/* The following code was generated by JFlex 1.6.1 */

/*--------------------------------------------------
 ------------  1ra Area: Codigo de Usuario ---------
 ---------------------------------------------------*/

//------> Paquetes,importaciones
package Analizadores;
import java_cup.runtime.*;
import javax.swing.JOptionPane;

/*----------------------------------------------------------
  ------------  2da Area: Opciones y Declaraciones ---------
  ----------------------------------------------------------*/

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/Analizadores/A_Lexico_FCA.jflex</tt>
 */
public class Analizador_Lexico_FCA implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0, 44,  2, 46, 44,  8,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
    45,  0,  1,  9, 19,  0,  0,  0, 13, 14,  0,  0, 10,  0,  4,  0, 
     3,  3,  3,  3,  3,  3,  3,  3,  3,  3, 16, 15,  0, 20,  0,  0, 
     0, 25, 37, 34, 31, 22, 36, 21,  6, 33, 40,  6, 39, 35, 23, 27, 
    26,  6, 24, 30, 28, 38, 42,  6, 41, 43,  6, 17,  0, 18,  0,  7, 
     0, 25, 37, 34, 31, 22, 36, 21,  6, 33, 40,  6, 39, 35, 23, 27, 
    26,  6, 24, 30, 28, 38, 42,  6, 41, 43,  6, 11,  5, 12,  0,  0, 
     0,  0,  0,  0,  0, 46,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\2\1\1\2\1\3\1\4\1\1\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\4\4\1\1\4\4\2\0\1\20\4\4\1\0"+
    "\1\4\1\0\5\4\1\21\1\22\2\20\4\4\1\0"+
    "\1\4\1\0\7\4\1\23\1\4\1\0\1\4\1\0"+
    "\1\4\1\0\5\4\1\0\2\4\1\0\1\4\1\0"+
    "\1\4\1\0\5\4\1\0\2\4\2\24\2\25\1\0"+
    "\1\4\1\26\3\4\1\0\2\4\1\27\1\30\1\27"+
    "\1\30\1\0\1\4\1\31\2\32\1\4\1\0\3\4"+
    "\1\0\2\4\1\0\2\4\1\0\1\4\1\0\2\4"+
    "\1\0\2\4\1\0\1\4\1\0\2\4\1\0\2\4"+
    "\1\0\1\4\1\0\2\4\1\0\2\4\1\0\1\4"+
    "\1\0\2\4\2\33\1\4\1\0\1\4\1\0\2\4"+
    "\1\34\1\0\1\4\1\0\2\4\1\0\1\4\2\35"+
    "\1\0\1\4\1\0\1\4\1\0\1\4\2\36\1\0"+
    "\1\4\1\0\1\4\1\0\1\4\1\0\1\4\1\0"+
    "\1\4\1\0\1\4\1\0\1\4\2\37";

  private static int [] zzUnpackAction() {
    int [] result = new int[192];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\57\0\215\0\274\0\353\0\57"+
    "\0\57\0\57\0\57\0\57\0\57\0\57\0\57\0\57"+
    "\0\57\0\57\0\u011a\0\u0149\0\u0178\0\u01a7\0\u01d6\0\u0205"+
    "\0\u0234\0\u0263\0\u0292\0\u02c1\0\u02f0\0\u031f\0\u034e\0\u037d"+
    "\0\u03ac\0\u03db\0\u040a\0\u0439\0\u0468\0\u0497\0\u04c6\0\u04f5"+
    "\0\u0524\0\u0553\0\57\0\u02f0\0\57\0\u0582\0\u05b1\0\u05e0"+
    "\0\u060f\0\u063e\0\u066d\0\u069c\0\u06cb\0\u06fa\0\u0729\0\u0758"+
    "\0\u0787\0\u07b6\0\u07e5\0\u0814\0\274\0\u0843\0\u0872\0\u08a1"+
    "\0\u08d0\0\u08ff\0\u092e\0\u095d\0\u098c\0\u09bb\0\u09ea\0\u0a19"+
    "\0\u0a48\0\u0a77\0\u0aa6\0\u0ad5\0\u0b04\0\u0b33\0\u0b62\0\u0b91"+
    "\0\u0bc0\0\u0bef\0\u0c1e\0\u0c4d\0\u0c7c\0\u0cab\0\u0cda\0\u0d09"+
    "\0\u0d38\0\u0d67\0\57\0\274\0\u0d96\0\u0dc5\0\274\0\u0df4"+
    "\0\u0e23\0\u0e52\0\u0e81\0\u0eb0\0\u0edf\0\57\0\57\0\274"+
    "\0\274\0\u0f0e\0\u0f3d\0\274\0\57\0\274\0\u0f6c\0\u0f9b"+
    "\0\u0fca\0\u0ff9\0\u1028\0\u1057\0\u1086\0\u10b5\0\u10e4\0\u1113"+
    "\0\u1142\0\u1171\0\u11a0\0\u11cf\0\u11fe\0\u122d\0\u125c\0\u128b"+
    "\0\u12ba\0\u12e9\0\u1318\0\u1347\0\u1376\0\u13a5\0\u13d4\0\u1403"+
    "\0\u1432\0\u1461\0\u1490\0\u14bf\0\u14ee\0\u151d\0\u154c\0\u157b"+
    "\0\u15aa\0\u15d9\0\u1608\0\u1637\0\u1666\0\u1695\0\57\0\274"+
    "\0\u16c4\0\u16f3\0\u1722\0\u1751\0\u1780\0\u17af\0\274\0\u17de"+
    "\0\u180d\0\u183c\0\u186b\0\u189a\0\u18c9\0\u18f8\0\57\0\274"+
    "\0\u1927\0\u1956\0\u1985\0\u19b4\0\u19e3\0\u1a12\0\57\0\274"+
    "\0\u1a41\0\u1a70\0\u1a9f\0\u1ace\0\u1afd\0\u1b2c\0\u1b5b\0\u1b8a"+
    "\0\u1bb9\0\u1be8\0\u1c17\0\u1c46\0\u1c75\0\u1ca4\0\57\0\274";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[192];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\2\2\1\6\1\2\1\4"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\3\6\1\25"+
    "\1\6\1\26\1\27\1\30\1\31\1\2\1\6\1\32"+
    "\7\6\1\33\1\6\2\4\60\0\1\34\2\0\54\34"+
    "\3\0\1\5\1\35\55\0\1\6\2\0\2\6\15\0"+
    "\10\6\1\0\2\6\1\0\13\6\14\0\1\36\50\0"+
    "\1\6\2\0\2\6\15\0\1\6\1\37\1\6\1\40"+
    "\4\6\1\0\2\6\1\0\13\6\6\0\1\6\2\0"+
    "\2\6\15\0\10\6\1\0\2\6\1\0\7\6\1\41"+
    "\3\6\6\0\1\6\2\0\2\6\15\0\10\6\1\0"+
    "\2\6\1\0\5\6\1\42\5\6\6\0\1\6\2\0"+
    "\2\6\15\0\10\6\1\0\2\6\1\43\1\44\12\6"+
    "\37\0\1\45\25\0\1\6\2\0\2\6\15\0\7\6"+
    "\1\46\1\0\2\6\1\0\13\6\6\0\1\6\2\0"+
    "\2\6\15\0\1\6\1\47\4\6\1\50\1\6\1\0"+
    "\2\6\1\0\13\6\6\0\1\6\2\0\2\6\15\0"+
    "\6\6\1\51\1\6\1\0\2\6\1\0\13\6\6\0"+
    "\1\6\2\0\2\6\15\0\4\6\1\52\3\6\1\0"+
    "\2\6\1\0\13\6\3\0\1\34\1\53\1\0\54\34"+
    "\3\0\1\54\1\0\1\54\47\0\1\54\1\0\2\36"+
    "\1\55\5\36\1\56\46\36\3\0\1\6\2\0\2\6"+
    "\15\0\2\6\1\57\5\6\1\0\2\6\1\0\13\6"+
    "\6\0\1\6\2\0\2\6\15\0\4\6\1\60\3\6"+
    "\1\0\2\6\1\0\13\6\6\0\1\6\2\0\2\6"+
    "\15\0\1\6\1\61\6\6\1\0\2\6\1\0\13\6"+
    "\6\0\1\6\2\0\2\6\15\0\2\6\1\62\5\6"+
    "\1\0\2\6\1\0\13\6\37\0\1\63\25\0\1\6"+
    "\2\0\2\6\15\0\7\6\1\64\1\0\2\6\1\0"+
    "\13\6\33\0\1\65\31\0\1\6\2\0\2\6\15\0"+
    "\3\6\1\66\4\6\1\0\2\6\1\0\13\6\6\0"+
    "\1\6\2\0\2\6\15\0\10\6\1\0\2\6\1\0"+
    "\3\6\1\67\7\6\6\0\1\6\2\0\2\6\15\0"+
    "\10\6\1\0\2\6\1\0\5\6\1\70\5\6\6\0"+
    "\1\6\2\0\2\6\15\0\10\6\1\0\2\6\1\0"+
    "\2\6\1\71\10\6\6\0\1\6\2\0\2\6\15\0"+
    "\10\6\1\0\2\6\1\0\6\6\1\72\4\6\5\0"+
    "\1\55\57\0\1\6\2\0\2\6\15\0\1\6\1\73"+
    "\6\6\1\0\2\6\1\0\13\6\6\0\1\6\2\0"+
    "\2\6\15\0\10\6\1\0\2\6\1\0\3\6\1\74"+
    "\7\6\6\0\1\6\2\0\2\6\15\0\10\6\1\0"+
    "\2\6\1\0\10\6\1\75\2\6\6\0\1\6\2\0"+
    "\2\6\15\0\7\6\1\76\1\0\2\6\1\0\13\6"+
    "\51\0\1\77\13\0\1\6\2\0\2\6\15\0\10\6"+
    "\1\0\2\6\1\0\5\6\1\100\5\6\43\0\2\101"+
    "\20\0\1\6\2\0\2\6\15\0\10\6\1\0\2\6"+
    "\1\101\1\102\12\6\6\0\1\6\2\0\2\6\15\0"+
    "\10\6\1\0\2\6\1\103\1\104\12\6\6\0\1\6"+
    "\2\0\2\6\15\0\10\6\1\0\2\6\1\0\4\6"+
    "\1\105\6\6\6\0\1\6\2\0\2\6\15\0\5\6"+
    "\1\106\2\6\1\0\2\6\1\0\13\6\6\0\1\6"+
    "\2\0\2\6\15\0\6\6\1\107\1\6\1\0\2\6"+
    "\1\0\13\6\6\0\1\6\2\0\2\6\15\0\3\6"+
    "\1\110\4\6\1\0\2\6\1\0\13\6\6\0\1\6"+
    "\2\0\2\6\15\0\10\6\1\0\2\6\1\111\1\112"+
    "\12\6\6\0\1\6\2\0\2\6\15\0\4\6\1\113"+
    "\3\6\1\0\2\6\1\0\13\6\52\0\1\114\12\0"+
    "\1\6\2\0\2\6\15\0\10\6\1\0\2\6\1\0"+
    "\6\6\1\115\4\6\32\0\1\116\32\0\1\6\2\0"+
    "\2\6\15\0\2\6\1\117\5\6\1\0\2\6\1\0"+
    "\13\6\32\0\1\120\32\0\1\6\2\0\2\6\15\0"+
    "\2\6\1\121\5\6\1\0\2\6\1\0\13\6\6\0"+
    "\1\6\2\0\2\6\15\0\10\6\1\0\2\6\1\0"+
    "\6\6\1\122\4\6\6\0\1\6\2\0\2\6\15\0"+
    "\4\6\1\123\3\6\1\0\2\6\1\0\13\6\6\0"+
    "\1\6\2\0\2\6\15\0\3\6\1\124\4\6\1\0"+
    "\2\6\1\0\13\6\6\0\1\6\2\0\2\6\15\0"+
    "\4\6\1\125\3\6\1\0\2\6\1\0\13\6\45\0"+
    "\1\126\17\0\1\6\2\0\2\6\15\0\10\6\1\0"+
    "\2\6\1\0\1\6\1\127\11\6\6\0\1\6\2\0"+
    "\2\6\15\0\10\6\1\0\2\6\1\0\7\6\1\130"+
    "\3\6\36\0\1\131\26\0\1\6\2\0\2\6\15\0"+
    "\6\6\1\132\1\6\1\0\2\6\1\0\13\6\30\0"+
    "\1\133\34\0\1\6\2\0\2\6\15\0\1\134\7\6"+
    "\1\0\2\6\1\0\13\6\43\0\2\135\20\0\1\6"+
    "\2\0\2\6\15\0\10\6\1\0\2\6\1\135\1\136"+
    "\12\6\6\0\1\6\2\0\2\6\15\0\1\6\1\137"+
    "\6\6\1\0\2\6\1\0\13\6\6\0\1\6\2\0"+
    "\2\6\15\0\3\6\1\140\4\6\1\0\2\6\1\0"+
    "\13\6\6\0\1\6\2\0\2\6\15\0\1\6\1\141"+
    "\6\6\1\0\2\6\1\0\13\6\6\0\1\6\2\0"+
    "\2\6\15\0\3\6\1\142\4\6\1\0\2\6\1\0"+
    "\13\6\34\0\1\143\30\0\1\6\2\0\2\6\15\0"+
    "\4\6\1\144\3\6\1\0\2\6\1\0\13\6\6\0"+
    "\1\6\2\0\2\6\15\0\1\6\1\145\6\6\1\0"+
    "\2\6\1\0\13\6\54\0\1\146\1\0\1\147\6\0"+
    "\1\6\2\0\2\6\15\0\10\6\1\0\2\6\1\0"+
    "\10\6\1\150\1\6\1\151\33\0\1\152\31\0\1\6"+
    "\2\0\2\6\15\0\3\6\1\153\4\6\1\0\2\6"+
    "\1\0\13\6\6\0\1\6\2\0\2\6\15\0\1\6"+
    "\1\154\6\6\1\0\2\6\1\0\13\6\6\0\1\6"+
    "\2\0\2\6\15\0\10\6\1\155\1\156\1\6\1\0"+
    "\13\6\6\0\1\6\2\0\2\6\15\0\3\6\1\157"+
    "\4\6\1\0\2\6\1\0\13\6\50\0\1\160\14\0"+
    "\1\6\2\0\2\6\15\0\10\6\1\0\2\6\1\0"+
    "\4\6\1\161\6\6\6\0\1\6\2\0\2\6\15\0"+
    "\1\162\1\163\6\6\1\0\2\6\1\0\13\6\30\0"+
    "\1\164\34\0\1\6\2\0\2\6\15\0\1\165\7\6"+
    "\1\0\2\6\1\0\13\6\6\0\1\6\2\0\2\6"+
    "\15\0\1\6\1\166\6\6\1\0\2\6\1\0\13\6"+
    "\34\0\1\167\30\0\1\6\2\0\2\6\15\0\4\6"+
    "\1\170\3\6\1\0\2\6\1\0\13\6\6\0\1\6"+
    "\2\0\2\6\15\0\1\6\1\171\6\6\1\0\2\6"+
    "\1\0\13\6\6\0\1\6\2\0\2\6\15\0\10\6"+
    "\1\172\1\173\1\6\1\0\13\6\52\0\1\174\12\0"+
    "\1\6\2\0\2\6\15\0\10\6\1\0\2\6\1\0"+
    "\6\6\1\175\4\6\6\0\1\6\2\0\2\6\15\0"+
    "\5\6\1\176\2\6\1\0\2\6\1\0\13\6\33\0"+
    "\1\177\31\0\1\6\2\0\2\6\15\0\3\6\1\200"+
    "\4\6\1\0\2\6\1\0\13\6\6\0\1\6\2\0"+
    "\2\6\15\0\2\6\1\201\5\6\1\0\2\6\1\0"+
    "\13\6\35\0\1\202\27\0\1\6\2\0\2\6\15\0"+
    "\5\6\1\203\2\6\1\0\2\6\1\0\13\6\36\0"+
    "\1\204\26\0\1\6\2\0\2\6\15\0\6\6\1\205"+
    "\1\6\1\0\2\6\1\0\13\6\6\0\1\6\2\0"+
    "\2\6\15\0\6\6\1\206\1\6\1\0\2\6\1\0"+
    "\13\6\33\0\1\207\31\0\1\6\2\0\2\6\15\0"+
    "\3\6\1\210\4\6\1\0\2\6\1\0\13\6\6\0"+
    "\1\6\2\0\2\6\15\0\1\6\1\211\6\6\1\0"+
    "\2\6\1\0\13\6\31\0\1\212\33\0\1\6\2\0"+
    "\2\6\15\0\1\6\1\213\6\6\1\0\2\6\1\0"+
    "\13\6\50\0\1\214\14\0\1\6\2\0\2\6\15\0"+
    "\10\6\1\0\2\6\1\0\4\6\1\215\6\6\6\0"+
    "\1\6\2\0\2\6\15\0\3\6\1\216\4\6\1\0"+
    "\2\6\1\0\13\6\34\0\1\217\30\0\1\6\2\0"+
    "\2\6\15\0\4\6\1\220\3\6\1\0\2\6\1\0"+
    "\13\6\6\0\1\6\2\0\2\6\15\0\3\6\1\221"+
    "\4\6\1\0\2\6\1\0\13\6\45\0\1\222\17\0"+
    "\1\6\2\0\2\6\15\0\10\6\1\0\2\6\1\0"+
    "\1\6\1\223\11\6\34\0\1\224\30\0\1\6\2\0"+
    "\2\6\15\0\4\6\1\225\3\6\1\0\2\6\1\0"+
    "\13\6\6\0\1\6\2\0\2\6\15\0\7\6\1\226"+
    "\1\0\2\6\1\0\13\6\40\0\2\227\23\0\1\6"+
    "\2\0\2\6\15\0\10\6\1\227\1\230\1\6\1\0"+
    "\13\6\6\0\1\6\2\0\2\6\15\0\4\6\1\231"+
    "\3\6\1\0\2\6\1\0\13\6\43\0\2\232\20\0"+
    "\1\6\2\0\2\6\15\0\10\6\1\0\2\6\1\232"+
    "\1\233\12\6\52\0\1\234\12\0\1\6\2\0\2\6"+
    "\15\0\10\6\1\0\2\6\1\0\6\6\1\235\4\6"+
    "\6\0\1\6\2\0\2\6\15\0\1\6\1\236\6\6"+
    "\1\0\2\6\1\0\13\6\6\0\1\6\2\0\2\6"+
    "\15\0\10\6\1\0\2\6\1\0\6\6\1\237\4\6"+
    "\47\0\1\240\15\0\1\6\2\0\2\6\15\0\10\6"+
    "\1\0\2\6\1\0\3\6\1\241\7\6\31\0\1\242"+
    "\33\0\1\6\2\0\2\6\15\0\1\6\1\243\6\6"+
    "\1\0\2\6\1\0\13\6\6\0\1\6\2\0\2\6"+
    "\15\0\1\6\1\244\6\6\1\0\2\6\1\0\13\6"+
    "\43\0\2\245\20\0\1\6\2\0\2\6\15\0\10\6"+
    "\1\0\2\6\1\245\1\246\12\6\40\0\2\247\23\0"+
    "\1\6\2\0\2\6\15\0\10\6\1\247\1\250\1\6"+
    "\1\0\13\6\6\0\1\6\2\0\2\6\15\0\10\6"+
    "\1\251\1\252\1\6\1\0\13\6\45\0\1\253\17\0"+
    "\1\6\2\0\2\6\15\0\10\6\1\0\2\6\1\0"+
    "\1\6\1\254\11\6\37\0\1\255\25\0\1\6\2\0"+
    "\2\6\15\0\7\6\1\256\1\0\2\6\1\0\13\6"+
    "\36\0\1\257\26\0\1\6\2\0\2\6\15\0\6\6"+
    "\1\260\1\6\1\0\2\6\1\0\13\6\34\0\1\261"+
    "\30\0\1\6\2\0\2\6\15\0\4\6\1\262\3\6"+
    "\1\0\2\6\1\0\13\6\42\0\1\263\22\0\1\6"+
    "\2\0\2\6\15\0\10\6\1\0\1\6\1\264\1\0"+
    "\13\6\43\0\2\265\20\0\1\6\2\0\2\6\15\0"+
    "\10\6\1\0\2\6\1\265\1\266\12\6\40\0\2\267"+
    "\23\0\1\6\2\0\2\6\15\0\10\6\1\267\1\270"+
    "\1\6\1\0\13\6\37\0\1\271\25\0\1\6\2\0"+
    "\2\6\15\0\7\6\1\272\1\0\2\6\1\0\13\6"+
    "\43\0\2\273\20\0\1\6\2\0\2\6\15\0\10\6"+
    "\1\0\2\6\1\273\1\274\12\6\45\0\1\275\17\0"+
    "\1\6\2\0\2\6\15\0\10\6\1\0\2\6\1\0"+
    "\1\6\1\276\11\6\36\0\1\277\26\0\1\6\2\0"+
    "\2\6\15\0\6\6\1\300\1\6\1\0\2\6\1\0"+
    "\13\6\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7379];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\3\1\13\11\11\1\2\0"+
    "\5\1\1\0\1\1\1\0\5\1\1\11\1\1\1\11"+
    "\5\1\1\0\1\1\1\0\11\1\1\0\1\1\1\0"+
    "\1\1\1\0\5\1\1\0\2\1\1\0\1\1\1\0"+
    "\1\1\1\0\5\1\1\0\4\1\1\11\1\1\1\0"+
    "\5\1\1\0\2\1\2\11\2\1\1\0\2\1\1\11"+
    "\2\1\1\0\3\1\1\0\2\1\1\0\2\1\1\0"+
    "\1\1\1\0\2\1\1\0\2\1\1\0\1\1\1\0"+
    "\2\1\1\0\2\1\1\0\1\1\1\0\2\1\1\0"+
    "\2\1\1\0\1\1\1\0\2\1\1\11\2\1\1\0"+
    "\1\1\1\0\3\1\1\0\1\1\1\0\2\1\1\0"+
    "\1\1\1\11\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\11\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[192];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    //----> Codigo de usuario en sintaxis java


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Analizador_Lexico_FCA(java.io.Reader in) {
    this.zzReader = in;
  }



  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(Simbolos_FCA.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("Error Lexico"+yytext()+" Linea "+yyline+" Columna "+yycolumn);
            }
          case 32: break;
          case 2: 
            { /* Espacios en blanco, se ignoran */
            }
          case 33: break;
          case 3: 
            { System.out.println("Reconocio "+yytext()+" digito"); return new Symbol(Simbolos_FCA.digito, yycolumn, yyline, yytext());
            }
          case 34: break;
          case 4: 
            { System.out.println("Reconocio "+yytext()+" id"); return new Symbol(Simbolos_FCA.id, yycolumn, yyline, yytext());
            }
          case 35: break;
          case 5: 
            { System.out.println("Reconocio "+yytext()+" coma"); return new Symbol(Simbolos_FCA.coma, yycolumn, yyline, yytext());
            }
          case 36: break;
          case 6: 
            { System.out.println("Reconocio "+yytext()+" llava"); return new Symbol(Simbolos_FCA.llava, yycolumn, yyline, yytext());
            }
          case 37: break;
          case 7: 
            { System.out.println("Reconocio "+yytext()+" llavc"); return new Symbol(Simbolos_FCA.llavc, yycolumn, yyline, yytext());
            }
          case 38: break;
          case 8: 
            { System.out.println("Reconocio "+yytext()+" para"); return new Symbol(Simbolos_FCA.para, yycolumn, yyline, yytext());
            }
          case 39: break;
          case 9: 
            { System.out.println("Reconocio "+yytext()+" parc"); return new Symbol(Simbolos_FCA.parc, yycolumn, yyline, yytext());
            }
          case 40: break;
          case 10: 
            { System.out.println("Reconocio "+yytext()+" pyc"); return new Symbol(Simbolos_FCA.pyc, yycolumn, yyline, yytext());
            }
          case 41: break;
          case 11: 
            { System.out.println("Reconocio "+yytext()+" dospnts"); return new Symbol(Simbolos_FCA.dospnts, yycolumn, yyline, yytext());
            }
          case 42: break;
          case 12: 
            { System.out.println("Reconocio "+yytext()+" cora"); return new Symbol(Simbolos_FCA.cora, yycolumn, yyline, yytext());
            }
          case 43: break;
          case 13: 
            { System.out.println("Reconocio "+yytext()+" corc"); return new Symbol(Simbolos_FCA.corc, yycolumn, yyline, yytext());
            }
          case 44: break;
          case 14: 
            { System.out.println("Reconocio "+yytext()+" dolar"); return new Symbol(Simbolos_FCA.dolar, yycolumn, yyline, yytext());
            }
          case 45: break;
          case 15: 
            { System.out.println("Reconocio "+yytext()+" igual"); return new Symbol(Simbolos_FCA.igual, yycolumn, yyline, yytext());
            }
          case 46: break;
          case 16: 
            { System.out.println("Comentario: "+yytext());
            }
          case 47: break;
          case 17: 
            { System.out.println("Reconocio "+yytext()+" cadena"); return new Symbol(Simbolos_FCA.cadena, yycolumn, yyline, yytext());
            }
          case 48: break;
          case 18: 
            { System.out.println("Reconocio "+yytext()+" decimal"); return new Symbol(Simbolos_FCA.decimal, yycolumn, yyline, yytext());
            }
          case 49: break;
          case 19: 
            { System.out.println("Reconocio "+yytext()+" ejex"); return new Symbol(Simbolos_FCA.ejex, yycolumn, yyline, yytext());
            }
          case 50: break;
          case 20: 
            { System.out.println("Reconocio "+yytext()+" titulo"); return new Symbol(Simbolos_FCA.titulo, yycolumn, yyline, yytext());
            }
          case 51: break;
          case 21: 
            { System.out.println("Reconocio "+yytext()+" cadstring"); return new Symbol(Simbolos_FCA.cadstring, yycolumn, yyline, yytext());
            }
          case 52: break;
          case 22: 
            { System.out.println("Reconocio "+yytext()+" doble"); return new Symbol(Simbolos_FCA.doble, yycolumn, yyline, yytext());
            }
          case 53: break;
          case 23: 
            { System.out.println("Reconocio "+yytext()+" titulox"); return new Symbol(Simbolos_FCA.titulox, yycolumn, yyline, yytext());
            }
          case 54: break;
          case 24: 
            { System.out.println("Reconocio "+yytext()+" tituloy"); return new Symbol(Simbolos_FCA.tituloy, yycolumn, yyline, yytext());
            }
          case 55: break;
          case 25: 
            { System.out.println("Reconocio "+yytext()+" comp"); return new Symbol(Simbolos_FCA.comp, yycolumn, yyline, yytext());
            }
          case 56: break;
          case 26: 
            { System.out.println("Reconocio "+yytext()+" valores"); return new Symbol(Simbolos_FCA.valores, yycolumn, yyline, yytext());
            }
          case 57: break;
          case 27: 
            { System.out.println("Reconocio "+yytext()+" gbarras"); return new Symbol(Simbolos_FCA.gbarras, yycolumn, yyline, yytext());
            }
          case 58: break;
          case 28: 
            { System.out.println("Reconocio "+yytext()+" pntgen"); return new Symbol(Simbolos_FCA.pntgen, yycolumn, yyline, yytext());
            }
          case 59: break;
          case 29: 
            { System.out.println("Reconocio "+yytext()+" defglobal"); return new Symbol(Simbolos_FCA.defglobal, yycolumn, yyline, yytext());
            }
          case 60: break;
          case 30: 
            { System.out.println("Reconocio "+yytext()+" pntesp"); return new Symbol(Simbolos_FCA.pntesp, yycolumn, yyline, yytext());
            }
          case 61: break;
          case 31: 
            { System.out.println("Reconocio "+yytext()+" gre"); return new Symbol(Simbolos_FCA.gre, yycolumn, yyline, yytext());
            }
          case 62: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
