
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int pyc = 16;
  public static final int parc = 8;
  public static final int para = 7;
  public static final int cadena = 11;
  public static final int decimal = 9;
  public static final int constante = 14;
  public static final int por = 5;
  public static final int llava = 19;
  public static final int menos = 4;
  public static final int digito = 2;
  public static final int div = 6;
  public static final int menorque = 17;
  public static final int igual = 15;
  public static final int EOF = 0;
  public static final int id = 10;
  public static final int let = 12;
  public static final int mayorque = 18;
  public static final int error = 1;
  public static final int mas = 3;
  public static final int var = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "digito",
  "mas",
  "menos",
  "por",
  "div",
  "para",
  "parc",
  "decimal",
  "id",
  "cadena",
  "let",
  "var",
  "constante",
  "igual",
  "pyc",
  "menorque",
  "mayorque",
  "llava"
  };
}

