
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos_FCA {
  /* terminals */
  public static final int coma = 2;
  public static final int llavc = 4;
  public static final int llava = 3;
  public static final int cadena = 10;
  public static final int gre = 8;
  public static final int EOF = 0;
  public static final int comp = 9;
  public static final int error = 1;
  public static final int parc = 6;
  public static final int pyc = 7;
  public static final int para = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "coma",
  "llava",
  "llavc",
  "para",
  "parc",
  "pyc",
  "gre",
  "comp",
  "cadena"
  };
}

