
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

import java_cup.runtime.Symbol;
import olc1_clase4.Comparar;
import java.util.LinkedList;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Sintactico_FCA extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return Simbolos_FCA.class;
}

  /** Default constructor. */
  @Deprecated
  public Sintactico_FCA() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Sintactico_FCA(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Sintactico_FCA(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\006\000\002\002\004\000\002\002\006\000\002\003" +
    "\004\000\002\003\003\000\002\004\003\000\002\005\011" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\021\000\004\012\004\001\002\000\004\005\007\001" +
    "\002\000\004\002\006\001\002\000\004\002\001\001\002" +
    "\000\004\013\011\001\002\000\006\006\ufffd\013\ufffd\001" +
    "\002\000\004\007\016\001\002\000\006\006\ufffe\013\ufffe" +
    "\001\002\000\006\006\015\013\011\001\002\000\006\006" +
    "\uffff\013\uffff\001\002\000\004\002\000\001\002\000\004" +
    "\014\017\001\002\000\004\004\020\001\002\000\004\014" +
    "\021\001\002\000\004\010\022\001\002\000\004\011\023" +
    "\001\002\000\006\006\ufffc\013\ufffc\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\021\000\004\002\004\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\003\012\004\011" +
    "\005\007\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\004\013\005\007\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Sintactico_FCA$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Sintactico_FCA$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Sintactico_FCA$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



        public String resultado = "";
        public static LinkedList<Object> instrucciones;
        
        

        public void syntax_error(Symbol s)
        {
            System.err.println("Error en la Linea " + (s.right+1) +" Columna "+(s.left+1)+ ". Identificador "+s.value + " no reconocido. Se ha recuperado del error." );
        }

        public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception
        {
            System.err.println("Error en la Linea " + (s.right+1)+ " Columna "+(s.left+1)+". Identificador " +s.value + " no reconocido.");
        }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Sintactico_FCA$actions {

  
  private final Sintactico_FCA parser;

  /** Constructor */
  CUP$Sintactico_FCA$actions(Sintactico_FCA parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Sintactico_FCA$do_action_part00000000(
    int                        CUP$Sintactico_FCA$act_num,
    java_cup.runtime.lr_parser CUP$Sintactico_FCA$parser,
    java.util.Stack            CUP$Sintactico_FCA$stack,
    int                        CUP$Sintactico_FCA$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Sintactico_FCA$result;

      /* select the action based on the action number */
      switch (CUP$Sintactico_FCA$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)).value;
		RESULT = start_val;
              CUP$Sintactico_FCA$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Sintactico_FCA$parser.done_parsing();
          return CUP$Sintactico_FCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= gre llava INSTRUCCIONES llavc 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)).right;
		LinkedList<Object> a = (LinkedList<Object>)((java_cup.runtime.Symbol) CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)).value;
		 instrucciones = a;  
              CUP$Sintactico_FCA$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), RESULT);
            }
          return CUP$Sintactico_FCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // INSTRUCCIONES ::= INSTRUCCIONES INSTRUCCION 
            {
              LinkedList<Object> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)).right;
		LinkedList<Object> a = (LinkedList<Object>)((java_cup.runtime.Symbol) CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$Sintactico_FCA$stack.peek()).value;
		 RESULT = a; RESULT.add(b); 
              CUP$Sintactico_FCA$result = parser.getSymbolFactory().newSymbol("INSTRUCCIONES",1, ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), RESULT);
            }
          return CUP$Sintactico_FCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // INSTRUCCIONES ::= INSTRUCCION 
            {
              LinkedList<Object> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$Sintactico_FCA$stack.peek()).value;
		 RESULT = new LinkedList<>(); RESULT.add(a);  
              CUP$Sintactico_FCA$result = parser.getSymbolFactory().newSymbol("INSTRUCCIONES",1, ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), RESULT);
            }
          return CUP$Sintactico_FCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // INSTRUCCION ::= COMPARE 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()).right;
		Comparar a = (Comparar)((java_cup.runtime.Symbol) CUP$Sintactico_FCA$stack.peek()).value;
		 RESULT = a; 
              CUP$Sintactico_FCA$result = parser.getSymbolFactory().newSymbol("INSTRUCCION",2, ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), RESULT);
            }
          return CUP$Sintactico_FCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // COMPARE ::= comp para cadena coma cadena parc pyc 
            {
              Comparar RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-4)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-4)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-4)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-2)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-2)).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-2)).value;
		 RESULT = new Comparar(a.substring(1,a.length()-1),b.substring(1,b.length()-1)); //le quitamos las comillas a las cadenas 
              CUP$Sintactico_FCA$result = parser.getSymbolFactory().newSymbol("COMPARE",3, ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.elementAt(CUP$Sintactico_FCA$top-6)), ((java_cup.runtime.Symbol)CUP$Sintactico_FCA$stack.peek()), RESULT);
            }
          return CUP$Sintactico_FCA$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Sintactico_FCA$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Sintactico_FCA$do_action(
    int                        CUP$Sintactico_FCA$act_num,
    java_cup.runtime.lr_parser CUP$Sintactico_FCA$parser,
    java.util.Stack            CUP$Sintactico_FCA$stack,
    int                        CUP$Sintactico_FCA$top)
    throws java.lang.Exception
    {
              return CUP$Sintactico_FCA$do_action_part00000000(
                               CUP$Sintactico_FCA$act_num,
                               CUP$Sintactico_FCA$parser,
                               CUP$Sintactico_FCA$stack,
                               CUP$Sintactico_FCA$top);
    }
}

}
